# =============================================================================
# VinFast EV Cost Tracking & Gas Savings Calculator
# For VinFast EVs using OCPP-compatible chargers with odometer tracking
# =============================================================================
#
# Add this to your configuration.yaml or use !include ocpp_sensors.yaml
#
# REQUIRES:
#   - VinFast Connected Car custom integration (for odometer)
#   - OCPP Integration (for charger energy)
#
# CUSTOMIZE THESE VALUES:
#   - electricity_rate: Your cost per kWh (check your utility bill)
#   - ev_efficiency: Your vehicle's efficiency in mi/kWh
#     - VinFast VF8: ~3.2-3.5 mi/kWh
#     - VinFast VF9: ~2.8-3.2 mi/kWh
#
# IMPORTANT: Update sensor entity IDs to match your setup:
#   - sensor.your_vehicle_name_odometer -> sensor.YOUR_VEHICLE_NAME_odometer
#   - sensor.charger_* -> your OCPP charger entity names
# =============================================================================

# Keep 35 days of history for accurate duration tracking
recorder:
  purge_keep_days: 35
  commit_interval: 1

# Adjustable input numbers (can be changed from dashboard)
input_number:
  gas_price_per_gallon:
    name: "Gas Price per Gallon"
    min: 1.00
    max: 10.00
    step: 0.01
    initial: 3.25
    unit_of_measurement: "$/gal"
    icon: mdi:gas-station

  comparable_vehicle_mpg:
    name: "Comparable Vehicle MPG"
    min: 10
    max: 60
    step: 1
    initial: 25
    unit_of_measurement: "mpg"
    icon: mdi:car

  ev_efficiency_mi_per_kwh:
    name: "EV Efficiency"
    min: 2.0
    max: 5.0
    step: 0.1
    initial: 3.5
    unit_of_measurement: "mi/kWh"
    icon: mdi:ev-station

# Template sensors for cost calculations
template:
  - sensor:
      # ===== ELECTRICITY RATE =====
      # CHANGE THIS to your actual electricity rate
      - name: "Electricity Rate"
        unique_id: electricity_rate
        unit_of_measurement: "$/kWh"
        state: "0.14601"  # <-- UPDATE THIS to your rate
        icon: mdi:currency-usd

      # ===== SESSION TRACKING =====
      - name: "Charging Session Cost"
        unique_id: charging_session_cost
        unit_of_measurement: "$"
        state: >
          {% set energy = states('sensor.charger_energy_session') | float(0) %}
          {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
          {{ (energy * rate) | round(2) }}
        icon: mdi:cash

      # ===== DAILY COST =====
      - name: "Daily Charging Cost"
        unique_id: daily_charging_cost
        unit_of_measurement: "$"
        state: >
          {% set energy = states('sensor.energy_stats_today') | float(0) %}
          {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
          {{ (energy * rate) | round(2) }}
        icon: mdi:cash-multiple

      # ===== 7 DAY COST =====
      - name: "Charging Cost 7 Days"
        unique_id: weekly_charging_cost
        unit_of_measurement: "$"
        state: >
          {% set energy = states('sensor.energy_stats_7_days') | float(0) %}
          {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
          {{ (energy * rate) | round(2) }}
        icon: mdi:cash-multiple

      # ===== 31 DAY COST =====
      - name: "Charging Cost 31 Days"
        unique_id: monthly_charging_cost
        unit_of_measurement: "$"
        state: >
          {% set energy = states('sensor.energy_stats_31_days') | float(0) %}
          {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
          {{ (energy * rate) | round(2) }}
        icon: mdi:cash-100

      # ===== ACTUAL EFFICIENCY FROM ODOMETER ==========

      # Actual Wh/mi (for battery degradation tracking over time)
      - name: "Actual Wh Per Mile"
        unique_id: actual_wh_per_mile
        unit_of_measurement: "Wh/mi"
        state_class: measurement
        state: >
          {% set kwh = states('sensor.energy_stats_31_days') | float(0) %}
          {% set miles = states('sensor.odometer_stats_31_days') | float(0) %}
          {% if miles > 0 and kwh > 0 %}
            {{ ((kwh * 1000) / miles) | round(0) }}
          {% else %}
            {{ (1000 / 3.5) | round(0) }}
          {% endif %}
        icon: mdi:lightning-bolt
        attributes:
          period: "31 days"
          miles_driven: "{{ states('sensor.odometer_stats_31_days') }}"
          kwh_charged: "{{ states('sensor.energy_stats_31_days') }}"

      # Actual efficiency mi/kWh (calculated from real odometer data)
      - name: "Actual Efficiency"
        unique_id: actual_efficiency_mi_kwh
        unit_of_measurement: "mi/kWh"
        state_class: measurement
        state: >
          {% set kwh = states('sensor.energy_stats_31_days') | float(0) %}
          {% set miles = states('sensor.odometer_stats_31_days') | float(0) %}
          {% if kwh > 0 and miles > 0 %}
            {{ (miles / kwh) | round(2) }}
          {% else %}
            3.5
          {% endif %}
        icon: mdi:ev-station

      # ===== COST PER MILE (from real odometer data) =====
      - name: "Cost Per Mile"
        unique_id: cost_per_mile
        unit_of_measurement: "$/mi"
        state: >
          {% set cost = states('sensor.monthly_charging_cost') | float(0) %}
          {% set miles = states('sensor.odometer_stats_31_days') | float(0) %}
          {% if miles > 0 %}
            {{ (cost / miles) | round(3) }}
          {% else %}
            {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
            {% set efficiency = states('input_number.ev_efficiency_mi_per_kwh') | float(3.5) %}
            {{ (rate / efficiency) | round(3) }}
          {% endif %}
        icon: mdi:road-variant
        attributes:
          source: "{{ 'actual' if states('sensor.odometer_stats_31_days') | float(0) > 0 else 'estimated' }}"

      # ===== COST PER 100 MILES =====
      - name: "Cost Per 100 Miles"
        unique_id: cost_per_100_miles
        unit_of_measurement: "$"
        state: >
          {% set cost = states('sensor.monthly_charging_cost') | float(0) %}
          {% set miles = states('sensor.odometer_stats_31_days') | float(0) %}
          {% if miles > 0 %}
            {{ ((cost / miles) * 100) | round(2) }}
          {% else %}
            {% set rate = states('sensor.electricity_rate') | float(0.14601) %}
            {% set efficiency = states('input_number.ev_efficiency_mi_per_kwh') | float(3.5) %}
            {{ ((rate / efficiency) * 100) | round(2) }}
          {% endif %}
        icon: mdi:road

      # ===== GAS SAVINGS CALCULATOR =====

      # Miles driven - uses utility meter first, then SQL, then estimate
      - name: "EV Miles Today"
        unique_id: ev_miles_today
        unit_of_measurement: "mi"
        state: >
          {% set meter = states('sensor.odometer_daily') | float(0) %}
          {% set sql = states('sensor.odometer_stats_today') | float(0) %}
          {% if meter > 0 %}
            {{ meter | round(1) }}
          {% elif sql > 0 %}
            {{ sql | round(1) }}
          {% else %}
            {% set kwh = states('sensor.energy_stats_today') | float(0) %}
            {% set efficiency = states('input_number.ev_efficiency_mi_per_kwh') | float(3.5) %}
            {{ (kwh * efficiency) | round(1) }}
          {% endif %}
        icon: mdi:road-variant
        attributes:
          source: >
            {% if states('sensor.odometer_daily') | float(0) > 0 %}odometer
            {% elif states('sensor.odometer_stats_today') | float(0) > 0 %}sql
            {% else %}estimated{% endif %}

      - name: "EV Miles 7 Days"
        unique_id: ev_miles_7_days
        unit_of_measurement: "mi"
        state: >
          {% set meter = states('sensor.odometer_weekly') | float(0) %}
          {% set sql = states('sensor.odometer_stats_7_days') | float(0) %}
          {% if meter > 0 %}
            {{ meter | round(1) }}
          {% elif sql > 0 %}
            {{ sql | round(1) }}
          {% else %}
            {% set kwh = states('sensor.energy_stats_7_days') | float(0) %}
            {% set efficiency = states('input_number.ev_efficiency_mi_per_kwh') | float(3.5) %}
            {{ (kwh * efficiency) | round(1) }}
          {% endif %}
        icon: mdi:road-variant
        attributes:
          source: >
            {% if states('sensor.odometer_weekly') | float(0) > 0 %}odometer
            {% elif states('sensor.odometer_stats_7_days') | float(0) > 0 %}sql
            {% else %}estimated{% endif %}

      - name: "EV Miles 31 Days"
        unique_id: ev_miles_31_days
        unit_of_measurement: "mi"
        state: >
          {% set meter = states('sensor.odometer_monthly') | float(0) %}
          {% set sql = states('sensor.odometer_stats_31_days') | float(0) %}
          {% if meter > 0 %}
            {{ meter | round(1) }}
          {% elif sql > 0 %}
            {{ sql | round(1) }}
          {% else %}
            {% set kwh = states('sensor.energy_stats_31_days') | float(0) %}
            {% set efficiency = states('input_number.ev_efficiency_mi_per_kwh') | float(3.5) %}
            {{ (kwh * efficiency) | round(1) }}
          {% endif %}
        icon: mdi:road-variant
        attributes:
          source: >
            {% if states('sensor.odometer_monthly') | float(0) > 0 %}odometer
            {% elif states('sensor.odometer_stats_31_days') | float(0) > 0 %}sql
            {% else %}estimated{% endif %}

      # What gas would have cost
      - name: "Gas Cost Today"
        unique_id: gas_cost_today
        unit_of_measurement: "$"
        state: >
          {% set miles = states('sensor.ev_miles_today') | float(0) %}
          {% set mpg = states('input_number.comparable_vehicle_mpg') | float(25) %}
          {% set gas_price = states('input_number.gas_price_per_gallon') | float(3.25) %}
          {% set gallons = miles / mpg %}
          {{ (gallons * gas_price) | round(2) }}
        icon: mdi:gas-station

      - name: "Gas Cost 7 Days"
        unique_id: gas_cost_7_days
        unit_of_measurement: "$"
        state: >
          {% set miles = states('sensor.ev_miles_7_days') | float(0) %}
          {% set mpg = states('input_number.comparable_vehicle_mpg') | float(25) %}
          {% set gas_price = states('input_number.gas_price_per_gallon') | float(3.25) %}
          {% set gallons = miles / mpg %}
          {{ (gallons * gas_price) | round(2) }}
        icon: mdi:gas-station

      - name: "Gas Cost 31 Days"
        unique_id: gas_cost_31_days
        unit_of_measurement: "$"
        state: >
          {% set miles = states('sensor.ev_miles_31_days') | float(0) %}
          {% set mpg = states('input_number.comparable_vehicle_mpg') | float(25) %}
          {% set gas_price = states('input_number.gas_price_per_gallon') | float(3.25) %}
          {% set gallons = miles / mpg %}
          {{ (gallons * gas_price) | round(2) }}
        icon: mdi:gas-station

      # Savings (gas cost - electric cost)
      - name: "Gas Savings Today"
        unique_id: gas_savings_today
        unit_of_measurement: "$"
        state: >
          {% set gas = states('sensor.gas_cost_today') | float(0) %}
          {% set electric = states('sensor.daily_charging_cost') | float(0) %}
          {{ (gas - electric) | round(2) }}
        icon: mdi:piggy-bank

      - name: "Gas Savings 7 Days"
        unique_id: gas_savings_7_days
        unit_of_measurement: "$"
        state: >
          {% set gas = states('sensor.gas_cost_7_days') | float(0) %}
          {% set electric = states('sensor.weekly_charging_cost') | float(0) %}
          {{ (gas - electric) | round(2) }}
        icon: mdi:piggy-bank

      - name: "Gas Savings 31 Days"
        unique_id: gas_savings_31_days
        unit_of_measurement: "$"
        state: >
          {% set gas = states('sensor.gas_cost_31_days') | float(0) %}
          {% set electric = states('sensor.monthly_charging_cost') | float(0) %}
          {{ (gas - electric) | round(2) }}
        icon: mdi:piggy-bank

      - name: "Gas Savings Percent"
        unique_id: gas_savings_percent
        unit_of_measurement: "%"
        state: >
          {% set gas = states('sensor.gas_cost_31_days') | float(0) %}
          {% set electric = states('sensor.monthly_charging_cost') | float(0) %}
          {% if gas > 0 %}
            {{ (((gas - electric) / gas) * 100) | round(0) }}
          {% else %}
            0
          {% endif %}
        icon: mdi:percent

      - name: "Gallons Saved 31 Days"
        unique_id: gallons_saved_31_days
        unit_of_measurement: "gal"
        state: >
          {% set miles = states('sensor.ev_miles_31_days') | float(0) %}
          {% set mpg = states('input_number.comparable_vehicle_mpg') | float(25) %}
          {{ (miles / mpg) | round(1) }}
        icon: mdi:barrel

# SQL sensors to query statistics database for accurate period energy
# NOTE: Replace 'sensor.your_vehicle_name_odometer' with your vehicle's odometer entity
sql:
  - name: "Energy Stats Today"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 2) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.charger_energy_active_import_register')
      AND start_ts >= strftime('%s', 'now', 'start of day', 'localtime')
    column: "value"
    unit_of_measurement: "kWh"

  - name: "Energy Stats 7 Days"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 2) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.charger_energy_active_import_register')
      AND start_ts >= strftime('%s', 'now', '-7 days', 'localtime')
    column: "value"
    unit_of_measurement: "kWh"

  - name: "Energy Stats 31 Days"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 2) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.charger_energy_active_import_register')
      AND start_ts >= strftime('%s', 'now', '-31 days', 'localtime')
    column: "value"
    unit_of_measurement: "kWh"

  # Odometer statistics for actual miles driven
  # IMPORTANT: Change 'sensor.your_vehicle_name_odometer' to match your VinFast entity name
  - name: "Odometer Stats Today"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 1) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.your_vehicle_name_odometer')
      AND start_ts >= strftime('%s', 'now', 'start of day', 'localtime')
    column: "value"
    unit_of_measurement: "mi"

  - name: "Odometer Stats 7 Days"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 1) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.your_vehicle_name_odometer')
      AND start_ts >= strftime('%s', 'now', '-7 days', 'localtime')
    column: "value"
    unit_of_measurement: "mi"

  - name: "Odometer Stats 31 Days"
    query: >
      SELECT ROUND(MAX(state) - MIN(state), 1) as value
      FROM statistics
      WHERE metadata_id = (SELECT id FROM statistics_meta WHERE statistic_id = 'sensor.your_vehicle_name_odometer')
      AND start_ts >= strftime('%s', 'now', '-31 days', 'localtime')
    column: "value"
    unit_of_measurement: "mi"

# History stats for charging duration tracking
sensor:
  - platform: history_stats
    name: "Charging Duration Today"
    entity_id: sensor.charger_status_connector
    state: "Charging"
    type: time
    start: "{{ today_at('00:00:00') }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: "Charging Duration 7 Days"
    entity_id: sensor.charger_status_connector
    state: "Charging"
    type: time
    start: "{{ today_at('00:00:00') - timedelta(days=7) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: "Charging Duration 31 Days"
    entity_id: sensor.charger_status_connector
    state: "Charging"
    type: time
    start: "{{ today_at('00:00:00') - timedelta(days=31) }}"
    end: "{{ now() }}"

# Utility meters for tracking energy and miles by period
# IMPORTANT: Change 'sensor.your_vehicle_name_odometer' to match your VinFast entity name
utility_meter:
  charger_energy_daily:
    source: sensor.charger_energy_active_import_register
    cycle: daily

  charger_energy_weekly:
    source: sensor.charger_energy_active_import_register
    cycle: weekly

  charger_energy_monthly:
    source: sensor.charger_energy_active_import_register
    cycle: monthly

  odometer_daily:
    source: sensor.your_vehicle_name_odometer
    cycle: daily

  odometer_weekly:
    source: sensor.your_vehicle_name_odometer
    cycle: weekly

  odometer_monthly:
    source: sensor.your_vehicle_name_odometer
    cycle: monthly
